Support command line options
LLNL/Caliper pull request #355
Opened 2021-04-12 15:31 UTC by DavidPoliakoff

So, Kokkos has added the ability to pass command-line arguments to tools. This just adds support for that functionality, taking a single argument and converting it into an argument to be passed to a ConfigManager

2021-04-13 17:28 UTC, daboehme requested changes
Let's put the `mgr` object into a proper namespace, otherwise looks good!

2021-04-13 17:28 UTC, daboehme commented on src/services/kokkos/KokkosProfilingSymbols.cpp
> +cali::ConfigManager mgr;
The `mgr` object should be in the `cali::kokkos` namespace.

2021-04-13 17:56 UTC, jrmadsen commented
Might want to also add the print help function to at least say "hey, you can pass in config manager params here"

2021-04-15 16:53 UTC, DavidPoliakoff commented
@daboehme , is there a "get me a list of config manager configurations" guy I can use for that?

2021-04-15 17:56 UTC, daboehme commented
@DavidPoliakoff there is `ConfigManager::available_config_specs()` and `ConfigManager::get_documentation_for_spec(const char*)`. See https://software.llnl.gov/Caliper/ConfigManagerAPI.html#_CPPv4NK4cali13ConfigManager22available_config_specsEv

2021-04-20 15:34 UTC, DavidPoliakoff commented
@daboehme : sorry for the slow turnaround on that

2021-04-20 18:28 UTC, daboehme approved these changes

2021-04-20 18:28 UTC, merged